export function buildPrompt({
  userPrompt,
  memory,
  history,
  summary,
  pdfContext,
  intent = ""
}) {
  const normalizedIntent = (intent || "").toLowerCase();

  // 1. Specialized Intent Prompt Templates
  if (normalizedIntent === "summary") {
    const parts = [
      "Create a concise summary of the conversation.",
      "Include:\n- user goals\n- preferences\n- projects\n- ongoing work\n- important context"
    ];
    if (summary && summary.trim()) {
      parts.push(`Older Conversation Summary (to merge/compress):\n\n${summary.trim()}`);
    }
    if (history && history.length > 0) {
      const historyStr = history
        .map(msg => `${msg.role}: ${msg.content}`)
        .join("\n");
      parts.push(`New Conversation Messages:\n\n${historyStr}`);
    }
    return parts.join("\n\n");
  }

  if (normalizedIntent === "memoryextraction") {
    return `Extract only long-term personal facts.

Store:
- name
- languages
- programming languages
- favorite technologies
- favorite database
- favorite framework
- hobbies
- goals
- preferences
- long-term interests

Do not store:
- temporary questions
- random conversation
- one-time requests

Message:
${userPrompt.trim()}

Return ONLY valid JSON.

Do not use:
- markdown
- code fences
- explanations
- comments

Valid example:

{
  "favorite_database": "PostgreSQL"
}

{}`;
  }

  if (normalizedIntent === "actionplanning" || normalizedIntent === "planning" && userPrompt.includes("actions")) {
    // Only use the planning template if the prompt was generated by planner or explicitly requested
    return `You are an AI planning engine.

Available actions:

research
web_search
summarize
analyze
plan
save_note
save_research_note
create_task
create_study_tasks
memory_lookup
pdf_search
email_draft

Definitions:

research: Search the web and generate a detailed report on a topic.
web_search: Perform a raw web search.
summarize: Summarize a topic, document, or content into key points.
analyze: Analyze something and provide insights.
plan: Create a structured plan, roadmap, or step-by-step guide.
save_note: Save specific text as a note.
save_research_note: Save the last research result as a note.
create_task: Create a single actionable task.
create_study_tasks: Extract and create multiple study tasks from research.
email_draft: Prepare an email draft for user confirmation before sending. Use when user wants to send, write, draft, or compose an email.

User Request:

${userPrompt.trim()}

Return ONLY valid JSON. No markdown. No code fences. No explanation.

Schema:
{
  "actions": [
    {
      "tool": "tool_name",
      "input": "input_text"
    }
  ]
}

Even if there is only ONE action, it must still be inside the actions array.

Examples:

User: Research Kubernetes and save notes
Output:
{
  "actions": [
    { "tool": "research", "input": "Kubernetes" },
    { "tool": "save_research_note", "input": "Kubernetes" }
  ]
}

User: Summarize machine learning
Output:
{
  "actions": [
    { "tool": "summarize", "input": "machine learning" }
  ]
}

User: Create a plan to learn React
Output:
{
  "actions": [
    { "tool": "plan", "input": "Learn React from scratch" }
  ]
}

User: Analyze the pros and cons of microservices
Output:
{
  "actions": [
    { "tool": "analyze", "input": "pros and cons of microservices" }
  ]
}

User: Add task finish DSA assignment
Output:
{
  "actions": [
    { "tool": "create_task", "input": "Finish DSA assignment" }
  ]
}

User: Draft an email to john@example.com about the project update
Output:
{
  "actions": [
    { "tool": "email_draft", "input": "Draft an email to john@example.com about the project update" }
  ]
}

User: Send email to alice@corp.com subject: Meeting Tomorrow body: Are you free at 3pm?
Output:
{
  "actions": [
    { "tool": "email_draft", "input": "Send email to alice@corp.com subject: Meeting Tomorrow body: Are you free at 3pm?" }
  ]
}`;
  }

  if (normalizedIntent === "toolrouting") {
    return `You are a routing engine.

Available tools:

memory
task
note
pdf
web
chat

Definitions:

memory:
- user is telling personal information
- user preferences
- favorite things
- goals
- profile updates

Examples:
"My favorite color is green"
"I like PostgreSQL"
"My name is Sushan Acharya"

task:
- create, update, complete tasks

Examples:
"Add task finish DAA assignment"

note:
- save notes

Examples:
"Remember this note"
"Save this note"

pdf:
- questions specifically about uploaded PDFs
- questions about course material stored in PDFs

Examples:
"Explain deadlock from my notes"

web:
- current events
- latest information
- internet search required
- live information
- news
- weather

Examples:
"Latest AI news"
"Current React version"
"Today's IPL score"
"Weather in Bangalore"

chat:
- all normal questions
- coding questions
- general knowledge
- explanations

Examples:
"What is GCD?"
"Explain recursion"
"Write a Java program"

Message:
${userPrompt.trim()}

Return ONLY one tool name.`;
  }

  if (normalizedIntent === "emaildraft" || normalizedIntent === "emailextraction") {
    return `You are a structured email field extractor.

Extract the following JSON fields from the user's email request.

STRICT RULES:
- Return ONLY valid JSON. Never use markdown. Never return code fences. Never explain.
- NEVER invent, guess, or fabricate email addresses.
- If the recipient's email address is NOT explicitly stated in the request, return "" for recipientEmail.
- Generate a complete, professional email body with a proper greeting and closing based on the context.
- If cc or bcc are not mentioned, return empty arrays [].
- If signature is not mentioned, return "".
- recipientName should be the name or role of the recipient (e.g. "Professor", "John Smith", "Boss").

JSON schema to extract:
{
  "recipientName": "string",
  "recipientEmail": "string — ONLY if explicitly provided in the request, otherwise empty string",
  "subject": "string — concise professional subject line",
  "body": "string — complete professional email body with greeting and sign-off",
  "cc": ["array of cc emails if mentioned, otherwise []"],
  "bcc": ["array of bcc emails if mentioned, otherwise []"],
  "signature": "string — if mentioned, otherwise empty string"
}

User request:
${userPrompt.trim()}

JSON only:`;
  }

  // 2. Default CIE Prompt Template
  const parts = [];

  if (memory && Object.keys(memory).length > 0) {
    parts.push(`User Profile:\n\n${JSON.stringify(memory, null, 2)}`);
  }

  if (summary && summary.trim()) {
    parts.push(`Conversation Summary:\n\n${summary.trim()}`);
  }

  if (pdfContext && pdfContext.trim()) {
    parts.push(`Retrieved Document Context:\n\n${pdfContext.trim()}`);
  }

  if (history && history.length > 0) {
    const historyStr = history
      .map(msg => `${msg.role}: ${msg.content}`)
      .join("\n");
    parts.push(`Recent Conversation:\n\n${historyStr}`);
  }

  parts.push(`Current User Message:\n\n${userPrompt.trim()}`);

  return parts.join("\n\n");
}
